FROM node:20.12.0-alpine3.19

WORKDIR /usr/src/app

COPY package.json package-lock.json turbo.json tsconfig.json ./

COPY apps ./apps
COPY packages ./packages

# Install dependencies
RUN npm ci --only=production

# Generate Prisma client
RUN npm run db:generate

# Build the bank webhook
RUN npm run build-bank-webhook

# Expose the port
EXPOSE 3002

CMD ["npm", "run", "start-bank-webhook"]